services:
  lucilease:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: lucilease
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./fixtures:/fixtures:ro
      - ./scripts:/scripts:ro
